columnSuffix: null
contentColumnType: string
fieldGroup: 5a955a55-a779-4306-bc97-85f7bfe41cb8 # Homepage
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d39a8bd0-718b-435d-b9b8-8c155ac0242e' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a hero image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:d39a8bd0-718b-435d-b9b8-8c155ac0242e' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:d39a8bd0-718b-435d-b9b8-8c155ac0242e' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
