columnSuffix: deaquetv
contentColumnType: text
fieldGroup: 5a955a55-a779-4306-bc97-85f7bfe41cb8 # Homepage
handle: heroDescription
instructions: 'Add a description of your site'
name: 'Hero Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
