columnSuffix: ufirujlv
contentColumnType: 'decimal(17,7)'
fieldGroup: 553e7666-f8a5-4aa9-97c3-858707c957b6 # Stockist
handle: latitude
instructions: ''
name: Latitude
searchable: false
settings:
  decimals: '7'
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
