columnSuffix: null
contentColumnType: string
fieldGroup: d46d7388-9e94-44c1-a78d-4c2aedb301e9 # Common
handle: navigationLinks
instructions: ''
name: 'Navigation Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigationlinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
