columnSuffix: null
contentColumnType: string
fieldGroup: d46d7388-9e94-44c1-a78d-4c2aedb301e9 # Common
handle: photo
instructions: ''
name: Photo
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d39a8bd0-718b-435d-b9b8-8c155ac0242e' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:d39a8bd0-718b-435d-b9b8-8c155ac0242e' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:d39a8bd0-718b-435d-b9b8-8c155ac0242e' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
