defaultPlacement: end
enableVersioning: true
handle: aboutUs
name: 'About Us'
propagationMethod: all
siteSettings:
  fae7e92b-ce5f-43b3-a902-b5b89f3faae4: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: pages\about_us.twig
    uriFormat: about-us
type: single
