defaultPlacement: end
enableVersioning: true
handle: contactUs
name: 'Contact Us'
propagationMethod: all
siteSettings:
  fae7e92b-ce5f-43b3-a902-b5b89f3faae4: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: pages\contact_us.twig
    uriFormat: contact-us
type: single
