defaultPlacement: end
enableVersioning: true
handle: ourProducts
name: 'Our Products'
propagationMethod: all
siteSettings:
  fae7e92b-ce5f-43b3-a902-b5b89f3faae4: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: product\index.twig
    uriFormat: our-products
type: single
