defaultPlacement: end
enableVersioning: true
handle: terms
name: Terms
propagationMethod: all
siteSettings:
  fae7e92b-ce5f-43b3-a902-b5b89f3faae4: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: pages\terms.twig
    uriFormat: terms
type: single
