defaultPlacement: end
enableVersioning: true
handle: thanks
name: Thanks
propagationMethod: all
siteSettings:
  fae7e92b-ce5f-43b3-a902-b5b89f3faae4: # Goodbeers
    enabledByDefault: true
    hasUrls: true
    template: pages\thanks.twig
    uriFormat: contact-us/thanks
type: single
